// Auto-generated by npm run build:data
// DO NOT edit manually. Source: data/models-metadata.json + data/models-prices.json

export interface ModelPrice {
  input: string;
  output: string;
  unit?: string;
}

export interface AIModel {
  id: string;
  name: string;
  slug: string;
  provider: string;
  logo?: string;
  description: string;
  category: ModelCategory;
  pricing: ModelPrice | ModelPrice[];
  contextWindow: string;
  multimodal: boolean;
  strengths: string[];
  benchmarkScore?: number;
  released?: string;
  url: string;
  freeTier?: string;
  updatedAt: string;
}

export type ModelCategory = 'text' | 'image' | 'video' | 'audio' | 'code' | 'multimodal' | 'open-source';

export const modelCategories: { id: ModelCategory; label: string; icon: string; description: string }[] = [
  { id: "text", label: "文本模型", icon: "Type", description: "LLM 对话、写作、推理" },
  { id: "image", label: "图像生成", icon: "Image", description: "AI 绘图、图像编辑" },
  { id: "video", label: "视频生成", icon: "Video", description: "AI 视频创作" },
  { id: "audio", label: "音频处理", icon: "Mic", description: "语音合成、音乐生成" },
  { id: "code", label: "代码助手", icon: "Code2", description: "编程辅助、代码生成" },
  { id: "multimodal", label: "多模态", icon: "Sparkles", description: "图文音视频综合理解" },
  { id: "open-source", label: "开源模型", icon: "Globe", description: "可自部署的开源模型" },
];

export const models: AIModel[] = [
  {
    "id": "o3-pro",
    "name": "o3 Pro",
    "slug": "o3-pro",
    "provider": "OpenAI",
    "logo": "",
    "description": "OpenAI 最强推理模型，数学、科学、编程全能",
    "category": "text",
    "pricing": {
      "input": "$20.00 / 1M tokens",
      "output": "$80.00 / 1M tokens"
    },
    "contextWindow": "200K tokens",
    "multimodal": true,
    "strengths": [
      "复杂推理",
      "数学",
      "科学",
      "编程"
    ],
    "benchmarkScore": 97,
    "released": "2025-03",
    "url": "https://platform.openai.com",
    "freeTier": "无",
    "updatedAt": "2026-08-05"
  },
  {
    "id": "o4-mini",
    "name": "o4 Mini",
    "slug": "o4-mini",
    "provider": "OpenAI",
    "logo": "",
    "description": "OpenAI 高效推理模型，性价比高",
    "category": "text",
    "pricing": {
      "input": "$1.10 / 1M tokens",
      "output": "$4.40 / 1M tokens"
    },
    "contextWindow": "200K tokens",
    "multimodal": true,
    "strengths": [
      "快速推理",
      "编程",
      "数学",
      "高性价比"
    ],
    "benchmarkScore": 92,
    "released": "2025-04",
    "url": "https://platform.openai.com",
    "freeTier": "无",
    "updatedAt": "2026-08-05"
  },
  {
    "id": "gpt-4.1",
    "name": "GPT-4.1",
    "slug": "gpt-4.1",
    "provider": "OpenAI",
    "logo": "",
    "description": "OpenAI 通用语言模型，平衡性能与成本",
    "category": "text",
    "pricing": {
      "input": "$2.00 / 1M tokens",
      "output": "$8.00 / 1M tokens"
    },
    "contextWindow": "1.0M tokens",
    "multimodal": true,
    "strengths": [
      "通用对话",
      "长文本",
      "多语言",
      "多模态"
    ],
    "benchmarkScore": 90,
    "released": "2025-04",
    "url": "https://platform.openai.com",
    "freeTier": "无",
    "updatedAt": "2026-08-05"
  },
  {
    "id": "claude-sonnet-4-20250514",
    "name": "Claude Sonnet 4",
    "slug": "claude-sonnet-4",
    "provider": "Anthropic",
    "logo": "",
    "description": "Anthropic 旗舰推理模型，擅长长文档分析",
    "category": "text",
    "pricing": {
      "input": "$3.00 / 1M tokens",
      "output": "$15.00 / 1M tokens"
    },
    "contextWindow": "1M tokens",
    "multimodal": true,
    "strengths": [
      "长文档分析",
      "代码",
      "推理",
      "安全对齐"
    ],
    "benchmarkScore": 94,
    "released": "2025-05",
    "url": "https://www.anthropic.com",
    "freeTier": "免费层：4K 消息/天",
    "updatedAt": "2026-08-05"
  },
  {
    "id": "claude-opus-4-20250514",
    "name": "Claude Opus 4",
    "slug": "claude-opus-4",
    "provider": "Anthropic",
    "logo": "",
    "description": "Anthropic 最强模型，顶级推理能力",
    "category": "text",
    "pricing": {
      "input": "$15.00 / 1M tokens",
      "output": "$75.00 / 1M tokens"
    },
    "contextWindow": "200K tokens",
    "multimodal": true,
    "strengths": [
      "顶级推理",
      "复杂任务",
      "学术研究",
      "代码审查"
    ],
    "benchmarkScore": 96,
    "released": "2025-05",
    "url": "https://www.anthropic.com",
    "freeTier": "无",
    "updatedAt": "2026-08-05"
  },
  {
    "id": "claude-haiku-4-20250514",
    "name": "Claude Haiku 3.5",
    "slug": "claude-haiku-3.5",
    "provider": "Anthropic",
    "logo": "",
    "description": "Anthropic 高速低成本模型",
    "category": "text",
    "pricing": {
      "input": "$0.8000 / 1M tokens",
      "output": "$4.00 / 1M tokens"
    },
    "contextWindow": "200K tokens",
    "multimodal": false,
    "strengths": [
      "快速响应",
      "低成本",
      "批量处理",
      "日常对话"
    ],
    "benchmarkScore": 80,
    "released": "2025-05",
    "url": "https://www.anthropic.com",
    "freeTier": "免费层：1K 消息/天",
    "updatedAt": "2026-08-05"
  },
  {
    "id": "gemini-2.5-pro",
    "name": "Gemini 2.5 Pro",
    "slug": "gemini-2.5-pro",
    "provider": "Google",
    "logo": "",
    "description": "Google 最强多模态模型，1M 上下文窗口",
    "category": "multimodal",
    "pricing": {
      "input": "$1.25 / 1M tokens",
      "output": "$10.00 / 1M tokens"
    },
    "contextWindow": "1.0M tokens",
    "multimodal": true,
    "strengths": [
      "超长上下文",
      "多模态",
      "Google 生态",
      "搜索整合"
    ],
    "benchmarkScore": 95,
    "released": "2025-06",
    "url": "https://ai.google.dev",
    "freeTier": "Gemini API: 15 RPM 免费",
    "updatedAt": "2026-08-05"
  },
  {
    "id": "gemini-2.5-flash",
    "name": "Gemini 2.5 Flash",
    "slug": "gemini-2.5-flash",
    "provider": "Google",
    "logo": "",
    "description": "Google 快速高效多模态模型",
    "category": "multimodal",
    "pricing": {
      "input": "$0.3000 / 1M tokens",
      "output": "$2.50 / 1M tokens"
    },
    "contextWindow": "1.0M tokens",
    "multimodal": true,
    "strengths": [
      "极速响应",
      "超低成本",
      "多模态",
      "批量处理"
    ],
    "benchmarkScore": 86,
    "released": "2025-06",
    "url": "https://ai.google.dev",
    "freeTier": "Gemini API: 15 RPM 免费",
    "updatedAt": "2026-08-05"
  },
  {
    "id": "gemini-2.0-flash-lite",
    "name": "Gemini 2.0 Flash Lite",
    "slug": "gemini-2.0-flash-lite",
    "provider": "Google",
    "logo": "",
    "description": "Google 轻量级多模态模型",
    "category": "multimodal",
    "pricing": {
      "input": "$0.0750 / 1M tokens",
      "output": "$0.3000 / 1M tokens"
    },
    "contextWindow": "1.0M tokens",
    "multimodal": true,
    "strengths": [
      "最低成本",
      "快速响应",
      "简单任务"
    ],
    "benchmarkScore": 76,
    "released": "2025-01",
    "url": "https://ai.google.dev",
    "freeTier": "Gemini API: 免费",
    "updatedAt": "2026-08-05"
  },
  {
    "id": "gpt-image-1",
    "name": "GPT-Image-1",
    "slug": "gpt-image-1",
    "provider": "OpenAI",
    "logo": "",
    "description": "OpenAI 图像生成模型，高质量文生图",
    "category": "image",
    "pricing": {
      "input": "$0.12 / image",
      "output": "",
      "unit": "1024×1024"
    },
    "contextWindow": "-",
    "multimodal": false,
    "strengths": [
      "高质量图像",
      "文本渲染",
      "风格多样",
      "编辑能力强"
    ],
    "released": "2025-04",
    "url": "https://platform.openai.com",
    "freeTier": "无",
    "updatedAt": "2026-08-05"
  },
  {
    "id": "flux-3",
    "name": "Flux.3",
    "slug": "flux-3",
    "provider": "Black Forest Labs",
    "logo": "",
    "description": "新一代高质量文生图模型",
    "category": "image",
    "pricing": {
      "input": "$0.05 / image",
      "output": "",
      "unit": "per image (API)"
    },
    "contextWindow": "-",
    "multimodal": false,
    "strengths": [
      "高质量",
      "开源权重",
      "风格多样",
      "社区支持"
    ],
    "released": "2025-05",
    "url": "https://www.blackforestlabs.ai",
    "freeTier": "开源可自部署",
    "updatedAt": "2026-08-05"
  },
  {
    "id": "midjourney-v6-5",
    "name": "Midjourney v6.5",
    "slug": "midjourney-v6-5",
    "provider": "Midjourney",
    "logo": "",
    "description": "艺术级 AI 图像生成",
    "category": "image",
    "pricing": {
      "input": "$8-$60 / month",
      "output": "",
      "unit": "subscription"
    },
    "contextWindow": "-",
    "multimodal": false,
    "strengths": [
      "艺术品质",
      "创意风格",
      "社区活跃",
      "迭代快"
    ],
    "released": "2025-03",
    "url": "https://www.midjourney.com",
    "freeTier": "无免费层",
    "updatedAt": "2026-08-05"
  },
  {
    "id": "dall-e-3",
    "name": "DALL-E 3",
    "slug": "dall-e-3",
    "provider": "OpenAI",
    "logo": "",
    "description": "OpenAI 文生图模型，支持自然语言指令",
    "category": "image",
    "pricing": {
      "input": "",
      "output": ""
    },
    "contextWindow": "-",
    "multimodal": false,
    "strengths": [
      "自然语言理解",
      "创意生成",
      "安全过滤",
      "集成 ChatGPT"
    ],
    "released": "2023-11",
    "url": "https://platform.openai.com",
    "freeTier": "ChatGPT Plus 赠送",
    "updatedAt": "2026-08-05"
  },
  {
    "id": "stable-diffusion-3.5",
    "name": "Stable Diffusion 3.5",
    "slug": "stable-diffusion-3.5",
    "provider": "Stability AI",
    "logo": "",
    "description": "开源图像生成模型，可自部署",
    "category": "open-source",
    "pricing": {
      "input": "$0.02 / image (API)",
      "output": "",
      "unit": "self-host: free"
    },
    "contextWindow": "-",
    "multimodal": false,
    "strengths": [
      "开源免费",
      "自部署",
      "ControlNet",
      "LoRA 生态"
    ],
    "released": "2024-11",
    "url": "https://stability.ai",
    "freeTier": "开源可自部署",
    "updatedAt": "2026-08-05"
  },
  {
    "id": "sora",
    "name": "Sora",
    "slug": "sora",
    "provider": "OpenAI",
    "logo": "",
    "description": "OpenAI 视频生成模型（已关停），2026 年 3 月停止服务",
    "category": "video",
    "pricing": {
      "input": "已关停",
      "output": "",
      "unit": "2026 年 3 月停止服务"
    },
    "contextWindow": "-",
    "multimodal": false,
    "strengths": [
      "高质量视频",
      "长片段",
      "物理模拟",
      "镜头控制"
    ],
    "released": "2025-04",
    "url": "https://platform.openai.com",
    "freeTier": "服务已停止",
    "updatedAt": "2026-08-05"
  },
  {
    "id": "veo-3",
    "name": "Veo 3",
    "slug": "veo-3",
    "provider": "Google",
    "logo": "",
    "description": "Google 视频生成模型，已纳入 Vertex AI 企业平台",
    "category": "video",
    "pricing": {
      "input": "$0.04 / sec",
      "output": "",
      "unit": "4K 视频"
    },
    "contextWindow": "-",
    "multimodal": false,
    "strengths": [
      "电影级画质",
      "60 秒视频",
      "音频同步",
      "多镜头",
      "4K 输出"
    ],
    "released": "2025-05",
    "url": "https://cloud.google.com/vertex-ai",
    "freeTier": "Vertex AI 免费试用",
    "updatedAt": "2026-08-05"
  },
  {
    "id": "kling-v1.5",
    "name": "Kling v1.5",
    "slug": "kling-v1.5",
    "provider": "Kuaishou",
    "logo": "",
    "description": "快手视频生成模型，支持长视频",
    "category": "video",
    "pricing": {
      "input": "¥0.8 / sec",
      "output": "",
      "unit": "per second"
    },
    "contextWindow": "-",
    "multimodal": false,
    "strengths": [
      "长视频生成",
      "中文理解",
      "性价比高",
      "动作自然"
    ],
    "released": "2025-03",
    "url": "https://klingai.com",
    "freeTier": "每日免费额度",
    "updatedAt": "2026-08-05"
  },
  {
    "id": "whisper-3",
    "name": "Whisper 3",
    "slug": "whisper-3",
    "provider": "OpenAI",
    "logo": "",
    "description": "OpenAI 语音识别模型",
    "category": "audio",
    "pricing": {
      "input": "",
      "output": ""
    },
    "contextWindow": "-",
    "multimodal": false,
    "strengths": [
      "高精度转录",
      "多语言",
      "实时处理",
      "开源"
    ],
    "benchmarkScore": 94,
    "released": "2023-11",
    "url": "https://platform.openai.com",
    "freeTier": "开源可自部署",
    "updatedAt": "2026-08-05"
  },
  {
    "id": "tts-1",
    "name": "ChatTTS",
    "slug": "chattts",
    "provider": "ChatTTS",
    "logo": "",
    "description": "高质量中文语音合成",
    "category": "audio",
    "pricing": {
      "input": "免费 (开源)",
      "output": "",
      "unit": "self-host: free"
    },
    "contextWindow": "-",
    "multimodal": false,
    "strengths": [
      "中文优化",
      "情感控制",
      "开源免费",
      "实时合成"
    ],
    "released": "2024-10",
    "url": "https://github.com/ChatTTS",
    "freeTier": "开源免费",
    "updatedAt": "2026-08-05"
  },
  {
    "id": "codex-2",
    "name": "Codex Mini v2",
    "slug": "codex-mini-v2",
    "provider": "OpenAI",
    "logo": "",
    "description": "OpenAI 代码专用模型",
    "category": "code",
    "pricing": {
      "input": "$1.50 / 1M tokens",
      "output": "$6.00 / 1M tokens"
    },
    "contextWindow": "200K tokens",
    "multimodal": true,
    "strengths": [
      "代码生成",
      "Bug 修复",
      "重构",
      "单元测试"
    ],
    "benchmarkScore": 89,
    "released": "2025-03",
    "url": "https://platform.openai.com",
    "freeTier": "无",
    "updatedAt": "2026-08-05"
  },
  {
    "id": "codestral",
    "name": "Codestral",
    "slug": "codestral",
    "provider": "Mistral",
    "logo": "",
    "description": "Mistral 代码生成模型，支持 80+ 语言",
    "category": "code",
    "pricing": {
      "input": "$0.0000 / 1M tokens",
      "output": "$0.0000 / 1M tokens"
    },
    "contextWindow": "32K tokens",
    "multimodal": false,
    "strengths": [
      "多语言",
      "超长上下文",
      "开源权重",
      "API 便宜"
    ],
    "benchmarkScore": 87,
    "released": "2024-06",
    "url": "https://mistral.ai",
    "freeTier": "Mistral API 免费层",
    "updatedAt": "2026-08-05"
  },
  {
    "id": "deepseek-coder-v3",
    "name": "DeepSeek Coder V3",
    "slug": "deepseek-coder-v3",
    "provider": "DeepSeek",
    "logo": "",
    "description": "DeepSeek 代码专用模型，性价比极高",
    "category": "code",
    "pricing": {
      "input": "$0.2700 / 1M tokens",
      "output": "$1.10 / 1M tokens"
    },
    "contextWindow": "65.5K tokens",
    "multimodal": false,
    "strengths": [
      "超低价",
      "代码生成",
      "开源",
      "中文优化"
    ],
    "benchmarkScore": 84,
    "released": "2024-09",
    "url": "https://www.deepseek.com",
    "freeTier": "API 免费额度",
    "updatedAt": "2026-08-05"
  },
  {
    "id": "llama-4-scout",
    "name": "Llama 4 Scout",
    "slug": "llama-4-scout",
    "provider": "Meta",
    "logo": "",
    "description": "Meta 开源大模型，社区生态最丰富",
    "category": "open-source",
    "pricing": {
      "input": "$0.2700 / 1M tokens",
      "output": "$0.8500 / 1M tokens"
    },
    "contextWindow": "131K tokens",
    "multimodal": false,
    "strengths": [
      "完全开源",
      "社区生态",
      "自部署免费",
      "多语言"
    ],
    "benchmarkScore": 88,
    "released": "2025-04",
    "url": "https://llama.meta.com",
    "freeTier": "完全开源免费",
    "updatedAt": "2026-08-05"
  },
  {
    "id": "qwen3",
    "name": "Qwen3",
    "slug": "qwen3",
    "provider": "Alibaba",
    "logo": "",
    "description": "阿里通义千问，中文能力顶尖",
    "category": "open-source",
    "pricing": {
      "input": "",
      "output": ""
    },
    "contextWindow": "-",
    "multimodal": false,
    "strengths": [
      "中文最强",
      "开源",
      "成本低",
      "多模态"
    ],
    "benchmarkScore": 85,
    "released": "2025-04",
    "url": "https://tongyi.aliyun.com",
    "freeTier": "开源 + API 免费额度",
    "updatedAt": "2026-08-05"
  },
  {
    "id": "glm-5",
    "name": "GLM-5",
    "slug": "glm-5",
    "provider": "Zhipu AI",
    "logo": "",
    "description": "智谱 AI 开源模型，中文理解优秀",
    "category": "open-source",
    "pricing": {
      "input": "免费 (自部署)",
      "output": "",
      "unit": "API: $0.05 / 1M tokens"
    },
    "contextWindow": "128K tokens",
    "multimodal": false,
    "strengths": [
      "中文理解",
      "开源",
      "极低 API 价",
      "ChatGLM 生态"
    ],
    "benchmarkScore": 82,
    "released": "2025-05",
    "url": "https://bigmodel.cn",
    "freeTier": "开源 + API 免费",
    "updatedAt": "2026-08-05"
  }
];

export function getModelBySlug(slug: string): AIModel | undefined {
  return models.find((m) => m.slug === slug);
}

export function getModelsByCategory(category: ModelCategory): AIModel[] {
  return models.filter((m) => m.category === category);
}

export function getAllCategories(): ModelCategory[] {
  return [...new Set(models.map((m) => m.category))];
}
